global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # FastAPI API metrics
  - job_name: "fastapi_app"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8000"]  

  # Prometheus internal metrics
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]